name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label: I have updated to the latest version of the plugin.
          required: true
        - label: I have read the README, especially the FAQ.
          required: true
        - label: >
            LSP inlay hints do work correctly without this plugin when using
            `vim.lsp.inlay_hint.enable(true)`. (If not, then the problem lies with your LSP or your LSP
            configuration, not this plugin.)
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations: { required: true }
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
    validations: { required: true }
  - type: textarea
    id: version-info
    attributes:
      label: neovim version
      render: Text
    validations: { required: true }
